# Generated by Django 4.1.1 on 2022-10-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='body',
            field=models.TextField(verbose_name='текст заметки'),
        ),
    ]
