# Generated by Django 4.1.1 on 2022-10-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_todo_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='закрыто'),
        ),
        migrations.AlterField(
            model_name='project',
            name='repo_link',
            field=models.CharField(blank=True, max_length=512, verbose_name='ссылка на репозиторий'),
        ),
    ]
